# TrySpace Sim Dockerfile w/ Pre-built Files
# https://github.com/TrySpaceOrg/tryspace-sim
#

FROM tryspace-lab:latest
LABEL maintainer="TrySpaceOrg" \
      description="Runtime image for TrySpace Simulators and Simulith"

# Copy built FSW files into the image
COPY build /opt/sim

# Set working directory
WORKDIR /opt/sim
