FROM tryspaceorg/tryspace-lab:1.0.0

# Copy built FSW files into the image
COPY build /app

# Set working directory
WORKDIR /app

# Set command to run with default number of clients (can be overridden)
CMD ["/app/simulith_server_standalone", "1"]
